version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./.env

  db:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver
    volumes:
      - /data:/data
    command: --verbose --file /data/landsat_grid.mbtiles --public_url https://satsync.org/tileserver/
    depends_on:
      - frontend

volumes:
  postgres_data:
