version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./.env

  backend:
    build: ./backend
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
